#!/usr/bin/env bash
# Installs nginx so that it redirects to another page

apt-get update
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
	listen		80 default_server;
	listen		[::]:80 default_server;
	root		/var/www/html;
	index		index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}

" > /etc/nginx/sites-available/default

service nginx restart
