#!/usr/bin/env bash
# Installs HAproxy and configures the two servers
apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 59834-web-01 54.165.119.73:80 check\n\tserver 59834-web-02 18.206.232.40:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
