#!/usr/bin/env bash
# Makes the nginx server run and listen on port 80
str1="listen 80 default_server;"
str="listen 8080 default_server;"
sudo sed -i "s/$str/$str1/" /etc/nginx/sites-enabled/default
sudo sed -i '22d' /etc/nginx/sites-enabled/default
sudo service nginx start
