#!/usr/bin/env bash
# This bash script makes a story based on the /etc/passwd file.

psWd="/etc/passwd"
while read -r usr1
do
	usr=$(echo "$usr1" | cut -d ":" -f 1)
	grpId=$(echo "$usr1" | cut -d ":" -f 4)
	home_dir=$(echo "$usr1" | cut -d ":" -f 6)
	sh=$(echo "$usr1" | cut -d ":" -f 7)
	usr_id=$(echo "$usr1" | cut -f 3 -d ":")
	password=$(echo "$usr1" | cut -f 2 -d ":")
	more_info=$(echo "$usr1" | cut -f 5 -d ":")
	echo "The user $usr is part of the $grpId gang, lives in $home_dir and rides $sh. $usr_id's place is protected by the passcode $password, more info about the user here: $more_info"
done < $psWd